### ISSUE TITLE
failed to run custom build command for `maidsafe_libsodium_sys v0.0.9`

### ISSUE THREAD

**Issue by southsideGLA** [maidsafe/sodiumoxide#13]
Latest git, last nights rust, Ubuntu 15.04

root@Maidsafe-test-wf001:/home/maid/maidsafe/sodiumoxide# cargo build --verbose
       Fresh byteorder v0.3.11
       Fresh libc v0.1.8
       Fresh rustc-serialize v0.3.15
       Fresh cbor v0.3.7
       Fresh pkg-config v0.3.5
   Compiling maidsafe_libsodium_sys v0.0.9
     Running `/home/maid/maidsafe/sodiumoxide/target/debug/build/maidsafe_libsodium_sys-26b32642e6ba71aa/build-script-build`
failed to run custom build command for `maidsafe_libsodium_sys v0.0.9`
Process didn't exit successfully: `/home/maid/maidsafe/sodiumoxide/target/debug/build/maidsafe_libsodium_sys-26b32642e6ba71aa/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"`: No such file or directory (os error 2)"', ../src/libcore/result.rs:731

**Comment by Fraser999** [comment]
Thanks for this report and apologies for not replying sooner - we only just assigned a maintainer to this library a couple of days ago, so the issue slipped past us.

I'm going to close this because we're deprecating this library in favour of the original fork since it has now been updated and published to crates.io.
